# Copyright 2023 Jean-Yves Franceschi, Mike Gartrell, Ludovic Dos Santos, Thibaut Issenhuth, Emmanuel de Bézenac,
# Mickaël Chen, Alain Rakotomamonjy

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


model: gan
model_params:
  model: vanilla
  latent_dim: 128
  nb_discr_steps: 1
  discriminator:
    name: mlp
    width: 512
    depth: 4
    batch_norm: false
    activation:
      name: leaky_relu
  generator:
    name: mlp
    width: 512
    depth: 4
    activation:
      name: leaky_relu
  init:
    name: normal
    gain: 0.02

dataset: gaussians
dataset_params:
  size: 500000
  nb: 5
  radius: 3
  std: 0.5

optim:
  batch_size: 128
  nb_steps: 1900
  optimizers:
    gen_optimizer:
      name: Adam
      settings:
        lr: 0.0002
        betas: [0.5, 0.999]
    discr_optimizer:
      name: Adam
      settings:
        lr: 0.0002
        betas: [0.5, 0.999]
  schedulers: ~

eval_freq: 270
eval:
  - config_name: 'standard'
    batch_size: 128
    nb_steps: 1
    nb_quali: 128
    tests: ['gen_quali']
    test_params:
      resoltion: 400
save_best: false

test:
  - config_name: 'standard'
    batch_size: 128
    nb_steps: 1
    nb_quali: 128
    tests: ['gen_quali']
    test_params:
      resoltion: 400
