# Copyright 2023 Jean-Yves Franceschi, Mike Gartrell, Ludovic Dos Santos, Thibaut Issenhuth, Emmanuel de Bézenac,
# Mickaël Chen, Alain Rakotomamonjy

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


model: score_gan
model_params:
  sigma_min: 0.32
  sigma_max: 40
  rho: 3
  score_data:
    name: ddpm
    sigma_min: 0.002
    sigma_max: 40
    sigma_data: 0.5
    embedding: positional
    embedding_size: 256
    model_channels: 16
    channel_mult: [1, 2, 2]
    channel_mult_emb: 4
    resample_filter: [1, 1]
    num_blocks: 1
    dropout: 0.13
    encoder_type: standard
    decoder_type: standard
  path_score_data: '/path/to/score/model.pt'
  latent_dim: 128
  generator:
    name: dcgan
    width: 64
    batch_norm: true
    spectral_norm: false
    activation:
      name: relu
    final_activation:
      name: tanh
  init_gen:
    name: normal
    gain: 0.02
  score_gen:
    name: ddpm
    sigma_min: 0.002
    sigma_max: 40
    sigma_data: 0.5
    embedding: positional
    embedding_size: 256
    model_channels: 64
    channel_mult: [1, 2, 2]
    channel_mult_emb: 4
    resample_filter: [1, 1]
    num_blocks: 2
    dropout: 0.13
    encoder_type: standard
    decoder_type: standard
  init_score:
    name: default
  nb_score_steps: 1

dataset: mnist
dataset_params:
  ratio_val: 0.1

optim:
  batch_size: 256
  nb_steps: 100000
  optimizers:
    score_optimizer:
      name: Adam
      settings:
        lr: 0.001
    gen_optimizer:
      name: Adam
      settings:
        lr: 0.0002
  schedulers: ~

eval_freq: 2500
eval:
  - config_name: 'standard'
    batch_size: 100
    nb_steps: 0
    nb_quali: 20
    metric: 'fid'
    tests: ['gen_quali', 'fid']
save_best: true

test:
  - config_name: 'standard'
    batch_size: 100
    nb_steps: 0
    nb_quali: 20
    tests: ['gen_quali', 'fid']
